build_from:
  amd64: ghcr.1ms.run/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.1ms.run/home-assistant/aarch64-base-debian:bookworm
  armv7: ghcr.1ms.run/home-assistant/armv7-base-debian:bookworm
