build_from:
  amd64: ghcr.nju.edu.cn/music-assistant/base:latest
  aarch64: ghcr.nju.edu.cn/music-assistant/base:latest
  armhf: ghcr.nju.edu.cn/music-assistant/base:latest
  armv7: ghcr.nju.edu.cn/music-assistant/base:latest
