---
build_from:
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base-python:3.13-alpine3.22
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base-python:3.13-alpine3.22
  armhf: ghcr.nju.edu.cn/home-assistant/armhf-base-python:3.13-alpine3.22
  armv7: ghcr.nju.edu.cn/home-assistant/armv7-base-python:3.13-alpine3.22
  i386: ghcr.nju.edu.cn/home-assistant/i386-base-python:3.13-alpine3.22
args:
  UNIVERSAL_SILABS_FLASHER: 0.0.36
