---
version: 0.4.0
slug: silabs_flasher
name: Silicon Labs Flasher
description: '[老王杂谈说]：Silicon Labs 固件烧录器附加程序'
url: >
  https://ghfast.top/github.com/home-assistant/addons/tree/master/silabs_flasher

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: true
hassio_api: true
image: docker.1ms.run/homeassistant/{arch}-addon-silabs-flasher
init: false
options:
  device: null
  bootloader_baudrate: "115200"
  flow_control: true
  verbose: false
schema:
  device: device(subsystem=tty)?
  bootloader_baudrate: list(57600|115200|230400|460800|921600)
  ezsp_baudrate: int?
  flow_control: bool?
  firmware_url: str?
  verbose: bool?
stage: experimental
startup: once
boot: manual
