arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: '[老王杂谈说]：将您的Immich画廊展示为数字相框'
hassio_api: true
image: ghcr.nju.edu.cn/alexbelgium/immich_frame-{arch}
init: false
map:
  - addon_config:rw
name: Immich Frame
ports:
  8080/tcp: 8171
ports_description:
  8080/tcp: Web UI port
schema:
  ApiKey: str
  ImmichServerUrl: str
  TZ: str?
slug: immich_frame
url: https://ghfast.top/github.com/alexbelgium/hassio-addons
version: "1.0.29.0"
webui: http://[HOST]:[PORT:8080]
