name: TOMMY
version: "0.5.0"
slug: tommysense-homeassistant-addon
description: '[老王杂谈说]：TOMMY (Home Assistant 插件)'
url: "https://ghfast.top/github.com/tommy-sense/homeassistant-addon"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
host_network: true # Needed for mDNS discovery
apparmor: true
ingress: true
ingress_port: 0
panel_icon: mdi:wifi-arrow-left-right
init: false
map:
  - type: data
    read_only: False
