name: PlanarAlly
version: "v2026.1.0"
upstream: 2024.3
slug: planarally
description: >-
  [老王杂谈说]：PlanarAlly 是一个开源的虚拟桌面 (VTT) 网页工具，旨在帮助您和您的玩家探索各种虚构世界。它设计为无需互联网访问即可使用，以适应您的幽暗地牢，并拥有多种增强沉浸感的功能，如光照和视野。
arch:
  - amd64
  - aarch64
url: "https://ghfast.top/github.com/jdeath/homeassistant-addons"
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
boot: manual
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8000]"
ingress: false
ingress_port: 8000
