name: Freenom-dns-updater
version: 1.6.10
slug: freenom-dns-updater
description: '[老王杂谈说]：Freenom 注册商域名管理 - 更新DNS记录，管理（添加/更新/删除）域名的DNS记录，自动续订域名等。'
url: https://ghfast.top/github.com/FaserF/hassio-addons/tree/master/freenom-dns-updater
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
map:
  - share:rw
ingress: false
init: false
panel_icon: mdi:web-box
options:
  config_file:
  update_time_in_seconds: 86400
schema:
  config_file: str
  update_time_in_seconds: int
