name: Otter Wiki
version: "2.20.3"
upstream: 2.7.0
slug: otterwiki
description: >-
  [老王杂谈说]：Otter Wiki是一种基于Python的协作内容管理软件，内容存储在跟踪所有更改的git仓库中，使用Markdown作为标记语言；它使用微框架Flask编写，CSS框架为halfmoon，编辑器为CodeMirror，图标由Font Awesome Free提供。
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.org/github.com/jdeath/homeassistant-addons"
ports:
  80/tcp: 8084
ports_description:
  80/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /app-data
image: redimp/otterwiki
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
ingress: false
ingress_port: 80
