name: Otter Wiki
version: "2.17.1"
upstream: 2.7.0
slug: otterwiki
description: >-
  [老王杂谈说]：Otter Wiki 是一个基于 Python 的协作式内容管理软件，即维基。内容存储在一个 Git 仓库中，该仓库会跟踪所有的更改。Markdown 被用作标记语言。Otter Wiki 是使用微框架 Flask 基于 Python 编写的。halfmoon 被用作 CSS 框架，CodeMirror 作为编辑器。Font Awesome Free 提供图标。
arch:
  - amd64
  - aarch64
url: "https://ghfast.top/github.com/jdeath/homeassistant-addons"
ports:
  80/tcp: 8084
ports_description:
  80/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /app-data
image: redimp/otterwiki
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
ingress: false
ingress_port: 80
