{
  "name": "gotify",
  "version": "2.6.1",
  "slug": "gotify",
  "codenotary": "djhui@live.cn",
  "description": "一个用go编写的消息服务端，也有客户端，通过gotify我们可以简单的进行收发消息。",
  "url": "https://github.com/ha-china/hassio-addons",
  "arch": ["aarch64", "amd64"],
  "startup": "application",
  "image": "ghcr.nju.edu.cn/gotify/server",
  "boot": "auto",
  "init": false,
  "ingress": true,
  "ingress_port": 80,
  "webui": "http://[HOST]:[PORT:7080]",
  "ports": {
    "7080/tcp": 80
  },
  "map": [
    "config:rw"
  ],
  "options": {
  },
  "schema": {
  },
  "environment": {
    "TZ": "Asia/Shanghai",
    "GOTIFY_DEFAULTUSER_PASS": "admin",
    "GOTIFY_DATABASE_CONNECTION": "/data/gotify.db",
    "GOTIFY_PLUGINSDIR": "/data/plugins",
    "GOTIFY_UPLOADEDIMAGESDIR": "/data/images"
  }
}