name: Tiny Tiny RSS
version: 0.1.1
slug: tt-rss
description: '[老王杂谈说]：基于网络的新闻源阅读器和聚合器'
url: https://tt-rss.org
arch:
  - aarch64
  - amd64
startup: services
options:
  self_url: ""
schema:
  self_url: str?
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:rss
image: ghcr.nju.edu.cn/faserf/hassio-addons-tt-rss-{arch}
