name: "GlassHome Dashboard (Edge)"
version: "0.9.7-beta.5"
slug: glasshome-edge
description: "[老王杂谈说]：null"
url: "https://gh-proxy.org/github.com/glasshome/glasshome-addon"
stage: experimental
arch:
  - amd64
  - aarch64
init: false
ingress: false
panel_icon: mdi:view-dashboard
startup: application
boot: auto
ports:
  3124/tcp: 3124
ports_description:
  3124/tcp: "Web interface (Edge)"
environment:
  PORT: "3124"
map:
  - data:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
image: "ghcr.1ms.run/glasshome/dash"
