---
build_from:
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base-debian:bookworm
  armhf: ghcr.nju.edu.cn/home-assistant/armhf-base-raspbian:bookworm
args:
  DECONZ_VERSION: 2.31.2
