name: "linkding"
version: "1.44.1"
upstream: "1.44.1"
slug: linkding
description: >-
  [老王杂谈说]：linkding 是一个你可以自己托管的收藏夹管理器。它的设计目标是简洁、快速，并使用 Docker 易于设置。
arch:
  - amd64
  - aarch64
url: "https://ghfast.top/github.com/jdeath/homeassistant-addons"
ports:
  9090/tcp: 9090
ports_description:
  9090/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /etc/linkding/data
image: sissbruecker/linkding
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:9090]"
ingress: false
ingress_port: 9090
