arch:
  - aarch64
  - amd64
  - armv7
codenotary: alexandrep.github@gmail.com
description: '[老王杂谈说]：Spotweb是一个基于Spotnet协议的分布式usenet社区'
hassio_api: true
image: ghcr.nju.edu.cn/alexbelgium/spotweb-{arch}
ingress: true
init: false
map:
  - ssl
  - config:rw
  - backup:rw
name: Spotweb
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
panel_admin: false
panel_icon: mdi:chart-timeline
panel_title: Spotweb
ports:
  80/tcp: 9999
ports_description:
  80/tcp: Not required for Ingress
schema:
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  remote_mysql_database: str?
  remote_mysql_host: str?
  remote_mysql_password: password?
  remote_mysql_port: int?
  remote_mysql_username: str?
  ssl: bool
services:
  - mysql:want
slug: spotweb
udev: true
url: https://ghfast.top/github.com/alexbelgium/hassio-addons/spotweb
version: 1.5.8-5
