build_from:
  armhf: "ghcr.nju.edu.cn/hassio-addons/base:18.2.1"
  armv7: "ghcr.nju.edu.cn/hassio-addons/base:18.2.1"
  aarch64: "ghcr.nju.edu.cn/hassio-addons/base:18.2.1"
  amd64: "ghcr.nju.edu.cn/hassio-addons/base:18.2.1"
  i386: "ghcr.nju.edu.cn/hassio-addons/base:18.2.1"
