name: Free Games Claimer Remaster
version: "dev"
upstream: dev
slug: freegamesclaimerremaster
description: >-
  [老王杂谈说]：无claim游戏来自Epic、Prime、GOG、Steam、育碧及更多
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.org/github.com/jdeath/homeassistant-addons"
ports:
  7080/tcp: 7080
ports_description:
  7080/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /fgc/data
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:7080]"
panel_admin: false
ingress: false
ingress_port: 7080
environment:
  TINI_SUBREAPER: "false"
udev: true
