name: Music Assistant (NIGHTLY)
version: 2.9.0.dev2026040404
slug: music_assistant_nightly
description: '[老王杂谈说]：Music Assistant 的每日构建版。如果你想跟上 Music Assistant 最新的前沿开发，请安装此版本！请自行承担风险使用，由于可能不稳定，不建议用于日常或生产环境。'
url: https://music-assistant.io
arch:
  - amd64
  - aarch64
homeassistant_api: true
discovery:
  - music_assistant
auth_api: true
host_network: true
ingress: true
ingress_port: 8094
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
map:
  - media:rw
  - ssl:ro
init: false
backup_exclude:
  - cache.db
  - collage_images/*
  - .cache/*
stage: experimental
image: ghcr.nju.edu.cn/music-assistant/server
tmpfs: true
options:
  log_level: info
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  safe_mode: bool
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
