name: Music Assistant (NIGHTLY)
version: 2.10.0.dev2026070706
slug: music_assistant_nightly
description: '[老王杂谈说]：Music Assistant 的每日构建版本。如果您想紧跟 Music Assistant 最前沿的开发，请安装此版本！使用风险自负，由于可能不稳定，不建议用于日常或生产环境。'
url: https://music-assistant.io
arch:
  - amd64
  - aarch64
homeassistant_api: true
discovery:
  - music_assistant
auth_api: true
host_network: true
ingress: true
ingress_port: 8094
audio: true
panel_icon: mdi:music-assistant
panel_title: Music Assistant
panel_admin: false
uart: false
map:
  - media:rw
  - ssl:ro
init: false
backup_exclude:
  - cache.db
  - collage_images/*
  - .cache/*
stage: experimental
image: ghcr.nju.edu.cn/music-assistant/server
tmpfs: true
options:
  log_level: info
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  safe_mode: bool
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
