name: Bambulab AMS Spoolman FilamentStatus
version: "1.2.1-1"
slug: bambulabspoolmanfs
description: "[老王杂谈说]：本项目将 Bambulab AMS 系统整合至 Spoolman，以实现线材卷盘用量同步。"
url: https://gh-proxy.org/github.com/bytenoodle/hassioaddon
arch:
  - amd64
  - aarch64
startup: services
init: false
map:
  - addon_config:rw
  - data:rw
ports:
  4000/tcp: 4000
webui: "http://[HOST]:[PORT:4000]"
options:
  PRINTER_ID: "printer-ID"
  PRINTER_CODE: "XYZ123"
  PRINTER_IP: "192.168.1.x"
  SPOOLMAN_ENDPOINT: "http://spoolmanurl:port"
  UPDATE_INTERVAL: 300000
  SET_LOCATION: false
  NEVER_MERGE_IF_TAG: false
  DEBUG: false
  MODE: "manual"
schema:
  PRINTER_ID: str
  PRINTER_CODE: str
  PRINTER_IP: str
  SPOOLMAN_ENDPOINT: str
  UPDATE_INTERVAL: int
  SET_LOCATION: bool
  NEVER_MERGE_IF_TAG: bool
  DEBUG: bool
  MODE: list(automatic|manual)
