name: "LiveBook"
version: "0.17.3"
upstream: "0.17.3"
slug: livebook
description: >-
  [老王杂谈说]：Livebook是一个用于编写交互式和协作代码笔记本的Web应用程序。
arch:
  - amd64
  - aarch64
url: "https://ghfast.top/github.com/jdeath/homeassistant-addons"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web Interface"
image: ghcr.nju.edu.cn/livebook-dev/livebook
map:
  - type: addon_config
    read_only: false
environment:
  LIVEBOOK_DATA_PATH: "/config/"
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
ingress: false
ingress_port: 8080
