name: "GlassHome Dashboard"
version: "0.9.6"
slug: glasshome
description: "[老王杂谈说]：null"
url: "https://gh-proxy.org/github.com/glasshome/glasshome-addon"
arch:
  - amd64
  - aarch64
init: false
ingress: false
panel_icon: mdi:view-dashboard
startup: application
boot: auto
ports:
  3123/tcp: 3123
ports_description:
  3123/tcp: "Web interface"
map:
  - data:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
image: "ghcr.1ms.run/glasshome/{arch}-glasshome"
